### ISSUE TITLE
gazebo stops working

### ISSUE THREAD

**Issue by mohammadrezaaerospace** [MikeS96/autonomous_landing_uav#11]
Hi @MikeS96 
Thank you for your help and responsiveness.
I did all steps:
https://github.com/MikeS96/autonomous_landing_uav/blob/master/Installation.md#models-configuration
and also I copied 1076_quad_f450_camera into
"Firmware/build/px4_sitl_default/etc/init.d-posix/airframes" (because of unknown error model)
And I copied Ros packages in catkin_ws/ src and executed catkin_make in catkin_ws directory.
Finally I copied gazebo folder files in   mavros_off_board/worlds/gazebo into  "/usr/share/gazebo-9/models"
 but after running  roslaunch mavros_off_board mavros_posix_sitl.launch
gazebo launch with black screen according to picture
Is there any other step that I did not do it?
[INFO] [1634912921.449012, 2755.525000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1634912921.605370081, 2755.525000000]: Camera Plugin: Using the 'robotNamespace' param: 'quad_f450_camera'
[ INFO] [1634912921.607587589, 2755.525000000]: Camera Plugin (ns = quad_f450_camera)  <tf_prefix_>, set to "quad_f450_camera"
nvc0_screen_create:1111 - Error allocating PGRAPH context for M2MF: -16
[vehicle_spawn_mrm_21152_5793566948683537121-5] process has finished cleanly
log file: /home/mrm/.ros/log/59c84e52-3344-11ec-9e28-b06ebfd20067/vehicle_spawn_mrm_21152_5793566948683537121-5*.log
Segmentation fault (core dumped)
[gazebo-3] process has died [pid 21194, exit code 139, cmd /opt/ros/melodic/lib/gazebo_ros/gzserver -e ode /home/mrm/Firmware/Tools/sitl_gazebo/worlds/grass_pad.world __name:=gazebo __log:=/home/mrm/.ros/log/59c84e52-3344-11ec-9e28-b06ebfd20067/gazebo-3.log].
log file: /home/mrm/.ros/log/59c84e52-3344-11ec-9e28-b06ebfd20067/gazebo-3*.log

but when I run command  roslaunch mavros_off_board urdf_launcher.launch , rviz and grass and aruco markers appears but anyway I can't run simulation 
best regards
![Screenshot from 2021-10-22 18-15-25](https://user-images.githubusercontent.com/75446046/138476073-127073f6-281c-41be-8064-355aae597116.png)
![Screenshot from 2021-10-22 17-52-21](https://user-images.githubusercontent.com/75446046/138476100-aa4956c7-f75d-44d7-a635-acf2d5cdf96f.png)
 
![Screenshot from 2021-10-22 18-24-35](https://user-images.githubusercontent.com/75446046/138476376-3b907428-2dce-439b-8fd3-a26b00e47087.png)
![Screenshot from 2021-10-22 18-25-27](https://user-images.githubusercontent.com/75446046/138476485-1de07310-06dd-4714-b474-0c6bb6da1599.png)

**Comment by MikeS96** [comment]
Hi @mohammadrezaaerospace,

Were you able to get the project running by disabling the plugin? 

Best.

**Comment by mohammadrezaaerospace** [comment]
> Hi @mohammadrezaaerospace,
> 
> Were you able to get the project running by disabling the plugin?
> 
> Best.

Hi @MikeS96 
No, I could not do it
The problem is still unsolved!
Best

**Comment by MikeS96** [comment]
Hey @mohammadrezaaerospace,

In case you are interested, I updated the project to Ubuntu 20 and ROS Noetic on its latest commit 3e36151. Fixed most of the issues discussed lately and manage to make the vehicle fly. Please consider installing OpenCV from source to enable SURF and SIFT descriptors as these provide better detections for the pad.
