### ISSUE TITLE
Error while running roslaunch object_detector simu.launch

### ISSUE THREAD

**Issue by AshwinDisa** [MikeS96/autonomous_landing_uav#12]
Hi @MikeS96
 
So i solved the earlier error(https://github.com/MikeS96/autonomous_landing_uav/issues/11) by changing the model to iris and adding a stereo camera to it and remapping the topic. The drone flew well along with the offboard mode. So basically the issue is with the quad_f450_camera model, I don't know what.

Now I'm facing a new error with the object detector package.

[ERROR] (2021-11-26 18:55:38.067) Descriptor exception: /home/ashd/slam_ws/src/opencv/modules/features2d/src/kaze/KAZEFeatures.cpp:556: error: (-215) 0 <= kpts[i].class_id && kpts[i].class_id < static_cast<int>(evolution_.size()) in function Feature_Description
. Maybe some keypoints are invalid for the selected descriptor extractor.

There is no such folder as slam_ws in my home directory! I moved it to a different location, reinstalled this repo but still getting the same error. Something to do with the opencv package.

Thanks in Advance

**Comment by MikeS96** [comment]
Hi @AshwinDisa ,

Thank you for your comments and feedback. I am still kind of unsure why the model is not working and that is very weird. Anyway, just to double-check, did you move to tag 11.1 with `git checkout tags/v1.11.0`? Another very important detail to make it work is Gazebo 9, Ros Melodic and Ubuntu 18 with Python 2. Also, can you please remove [these](https://github.com/MikeS96/autonomous_landing_uav/blob/master/mavros_off_board/sdf/quad_f450_camera.sdf#:~:text=%3Cplugin%20name%3D%22GstCameraPlugin,%3C/plugin%3E) lines in the quad_f450_camera.sdf and see if maybe it fix the plugin problem?

It seems to me that you installed find_object_2d from source. I did not do that so I never faced that issue. Can you please uninstall it and try again only using the commands:

```
sudo apt-get install ros-melodic-find-object-2d
sudo apt-get install ros-melodic-vision-opencv
```

Please do not hesitate to keep asking, and sorry for the inconvenience. Best.

**Comment by MikeS96** [comment]
Hi @AshwinDisa,

Studying a bit your error it indeed seems related to OpenCV and the KAZE feature detector. Can you try installing OpenCV from [source](https://www.pyimagesearch.com/2018/05/28/ubuntu-18-04-how-to-install-opencv/) and see if it works?

**Comment by AshwinDisa** [comment]
Hi @MikeS96,
Sorry i was a bit off due to exams, yes i will try reinstalling OpenCV and try again, Thanks for the help! About the previous comment, i did move to tag v1.11.0. And all other requirements were met, but the error sill persists.

**Comment by MikeS96** [comment]
Hey @AshwinDisa,

In case you are interested, I updated the project to Ubuntu 20 and ROS Noetic on its latest commit 3e36151. Fixed most of the issues discussed lately and manage to make the vehicle fly. Please consider installing OpenCV from source to enable SURF and SIFT descriptors as these provide better detections for the pad.
