### ISSUE TITLE
teleop

### ISSUE THREAD

**Issue by hoangnh1612** [MikeS96/autonomous_landing_uav#16]
Hi Mike!
Thank you for your great job!
I have followed your instruction and launch the model in gazebo successfully.
But when I run the teleop for take the px4 above the sign to detect, the uav seems to be auto return the initial position.
How can i do to solve it? 
Thanks a lot!!

**Comment by DuaneNielsen** [comment]
The teleop only works when the offboard node is not running.  If you have the offboard node running, I think offboard will fight for control of the vehicle.

I recommend plug your joystick or radio into your machine and control simulation using QGroundControl.  Start offboard when you ready to land.
