### ISSUE TITLE
Regarding placing Aruco Markers

### ISSUE THREAD

**Issue by Jaroan** [MikeS96/autonomous_landing_uav#2]
Hi, this is regarding the Aruco markers and the convajo marker.
I am trying to place it on a different model and one even on the quad. I am stuck with the relative addressing of the marker material files and unable to place it on another surface. Following a similar approach taken in this repo, I changed my relative addressing in the following lines from the grass_world file to add in my sdf file.
```
<material>
            <script>
              <uri>model://scripts</uri>
              <uri>model://textures</uri>
              <name>ArucoVisualMarker7/Marker</name>
            </script>
</material>
```
Any suggestions as to what should be my steps?

**Comment by MikeS96** [comment]
Hi Jaroan, 

In the folder `mavros_off_board/worlds` is a folder called _conejo_visual_marker_. This folder contains the custom landing pad as you mentioned. You can simply take the whole folder and copy in the following address:

`~/.gazebo/models`

Once the model is placed there open Gazebo, find the object (It appears as "Conejo Platform") and just place it wherever you want. Save the world file and that is it. If you want to change the pattern, just change the 'conejo.png' file inside the model's folder with the image of your election .

Hope it helps.

**Comment by Jaroan** [comment]
Hi!
I copied the marker and the marker pad models from the world file into a different SDF file and shifted the _conejo_visual_marker_ folder to 
`~/.gazebo/models
`
I was able to get the marker pad as required. Thank you very much!
