### ISSUE TITLE
SIFT features may require source build of ROS and OpenCV

### ISSUE THREAD

**Issue by DuaneNielsen** [MikeS96/autonomous_landing_uav#21]
Installed the project from a clean install of ubntu 20.4 and ROS noetic following instructions

Issued the command
```
roslaunch object_detector simu.launch
```
Then in the Find-Object menu selected View -> Parameters

The default detector was KAZU/KAZU and SIFT detector/features was not an available option.

![image](https://github.com/MikeS96/autonomous_landing_uav/assets/11070508/db431bf2-a263-4506-93fd-5d2602bf62cc)

This is apparently due to SIFT being part of the opencv_contrib library, no longer installed by default...

The solution was to build opencv and all the ROS libraries that depend on opencv from source.

Fortunately this is a lot easier than it sounds...

First, install opencv with the opencv_contrib modules using [these instructions](https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html)

Then checkout ros_perception into your catkin_ws and build clean

```
cd ~/catkin_ws/src
git clone https://github.com/ros-perception/vision_opencv.git -b noetic
cd ..
rm build
rm devel
catkin_make -DOpenCV_DIR=/usr/local/share/opencv4/
```

I think that should do it.. then Find-Object should have SIFT targets

![image](https://github.com/MikeS96/autonomous_landing_uav/assets/11070508/45a7ae5a-965e-44cb-8f17-c4d165c30733)

**Comment by ffYYq** [comment]
I still couldn‘t use that，error：image-view process has died

**Comment by MikeS96** [comment]
You are right @DuaneNielsen. SIFT features are only available if you build OpenCV from source. Thanks for sharing!
