### ISSUE TITLE
catkin_make error OpenCV version

### ISSUE THREAD

**Issue by jashshah999** [MikeS96/autonomous_landing_uav#4]
When I put autonomous_landing_uav in catkin_make/src and then run catkin_make in the root folder, I get the following error. Please help 

Base path: /home/ananthu/catkin_ws
Source space: /home/ananthu/catkin_ws/src
Build space: /home/ananthu/catkin_ws/build
Devel space: /home/ananthu/catkin_ws/devel
Install space: /home/ananthu/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/ananthu/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/ananthu/catkin_ws/devel;/opt/ros/melodic
-- This workspace overlays: /home/ananthu/catkin_ws/devel;/opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ananthu/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 3 packages in topological order:
-- ~~  - object_detector
-- ~~  - drone_controller
-- ~~  - mavros_off_board
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'object_detector'
-- ==> add_subdirectory(autonomous_landing_uav/object_detector)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at autonomous_landing_uav/object_detector/CMakeLists.txt:32 (find_package):
  Could not find a configuration file for package "OpenCV" that is compatible
  with requested version "3.4".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake, version: 4.5.2
    /usr/share/OpenCV/OpenCVConfig.cmake, version: 3.2.0

-- Configuring incomplete, errors occurred!
See also "/home/ananthu/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ananthu/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by offjangir** [comment]
faced the same error , change the version in  CMakeLists.txt of Object_detector pkg  to your OpenCV version.
It is basically looking for version 3.4 but finding some other version.

find_package(OpenCV 3.2 REQUIRED)

**Comment by zahidesatmutlu** [comment]
@jashshah999 how did you solved this problem?
