### ISSUE TITLE
Gazebo does not open up with the given commands

### ISSUE THREAD

**Issue by jashshah999** [MikeS96/autonomous_landing_uav#5]
After running $roslaunch mavros_off_board mavros_posix_sitl.launch, this is my log. Please help me out I really need to get this sorted. 

The gazebo SW opens but it hangs at "preparing your world" 

Please help 

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
process[gazebo-3]: started with pid [27586]
Info: found model autostart file as SYS_AUTOSTART=1076
INFO  [param] selected parameter default file eeprom/parameters_1076
[param] parameter file not found, creating eeprom/parameters_1076
process[gazebo_gui-4]: started with pid [27599]
  SYS_AUTOCONFIG: curr: 0 -> new: 1
process[vehicle_spawn_ananthu_inspiron_27544_2643451066337593827-5]: started with pid [27607]
process[mavros-6]: started with pid [27611]
ERROR: cannot launch node of type [image_view/image_view]: image_view
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/ananthu/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share
ROS path [3]=/home/ananthu/Downloads/PX4-Autopilot
ROS path [4]=/home/ananthu/Downloads/PX4-Autopilot/Tools/sitl_gazebo
  SYS_AUTOSTART: curr: 0 -> new: 1076
  CAL_ACC0_ID: curr: 0 -> new: 1310988
  CAL_GYRO0_ID: curr: 0 -> new: 1310988
  CAL_ACC1_ID: curr: 0 -> new: 1310996
  CAL_GYRO1_ID: curr: 0 -> new: 1310996
  CAL_ACC2_ID: curr: 0 -> new: 1311004
  CAL_GYRO2_ID: curr: 0 -> new: 1311004
  CAL_MAG0_ID: curr: 0 -> new: 197388
  CAL_MAG1_ID: curr: 0 -> new: 197644
  SENS_BOARD_X_OFF: curr: 0.0000 -> new: 0.0000
[ INFO] [1616142200.985455715]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1616142200.987320949]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1616142200.987483506]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1616142200.987632737]: GCS bridge disabled
  SENS_DPRES_OFF: curr: 0.0000 -> new: 0.0010
[ INFO] [1616142200.996044638]: Plugin 3dr_radio loaded
[ INFO] [1616142200.997235792]: Plugin 3dr_radio initialized
[ INFO] [1616142200.997338472]: Plugin actuator_control loaded
[ INFO] [1616142200.999575561]: Plugin actuator_control initialized
[ INFO] [1616142201.002585128]: Plugin adsb loaded
[ INFO] [1616142201.006838388]: Plugin adsb initialized
[ INFO] [1616142201.007898049]: Plugin altitude loaded
[ INFO] [1616142201.008848041]: Plugin altitude initialized
[ INFO] [1616142201.009015564]: Plugin cam_imu_sync loaded
[ INFO] [1616142201.009523838]: Plugin cam_imu_sync initialized
[ INFO] [1616142201.012846403]: Plugin command loaded
[ INFO] [1616142201.017367835]: Plugin command initialized
[ INFO] [1616142201.017607510]: Plugin companion_process_status loaded
[ INFO] [1616142201.019207060]: Plugin companion_process_status initialized
[ INFO] [1616142201.019372436]: Plugin debug_value loaded
[ INFO] [1616142201.028992638]: Plugin debug_value initialized
[ INFO] [1616142201.029117425]: Plugin distance_sensor blacklisted
[ INFO] [1616142201.029245016]: Plugin esc_status loaded
[ INFO] [1616142201.030261481]: Plugin esc_status initialized
[ INFO] [1616142201.030396307]: Plugin fake_gps loaded
[ INFO] [1616142201.043489802]: Plugin fake_gps initialized
[ INFO] [1616142201.043693432]: Plugin ftp loaded
[ INFO] [1616142201.047852312]: Plugin ftp initialized
[ INFO] [1616142201.047983072]: Plugin global_position loaded
[ INFO] [1616142201.060124430]: Plugin global_position initialized
[ INFO] [1616142201.060260302]: Plugin gps_rtk loaded
[ INFO] [1616142201.062821496]: Plugin gps_rtk initialized
[ INFO] [1616142201.062950954]: Plugin gps_status loaded
[ INFO] [1616142201.064698707]: Plugin gps_status initialized
[ INFO] [1616142201.064832740]: Plugin hil loaded
[ INFO] [1616142201.074081219]: Plugin hil initialized
[ INFO] [1616142201.074216461]: Plugin home_position loaded
[ INFO] [1616142201.076561549]: Plugin home_position initialized
[ INFO] [1616142201.076688176]: Plugin imu loaded
[ INFO] [1616142201.081719758]: Plugin imu initialized
[ INFO] [1616142201.081848062]: Plugin landing_target loaded
[ INFO] [1616142201.092192821]: Plugin landing_target initialized
[ INFO] [1616142201.092342040]: Plugin local_position loaded
  MC_PITCHRATE_P: curr: 0.1500 -> new: 0.1000
  MC_ROLLRATE_P: curr: 0.1500 -> new: 0.1000
[ INFO] [1616142201.097091220]: Plugin local_position initialized
[ INFO] [1616142201.097216195]: Plugin log_transfer loaded
* SYS_AUTOCONFIG: curr: 1 -> new: 0
[ INFO] [1616142201.099389429]: Plugin log_transfer initialized
[ INFO] [1616142201.099521707]: Plugin manual_control loaded
[ INFO] [1616142201.101480969]: Plugin manual_control initialized
[ INFO] [1616142201.101609628]: Plugin mocap_pose_estimate loaded
[ INFO] [1616142201.104052458]: Plugin mocap_pose_estimate initialized
[ INFO] [1616142201.104183044]: Plugin mount_control loaded
  IMU_INTEG_RATE: curr: 200 -> new: 250
[ INFO] [1616142201.110976360]: Plugin mount_control initialized
[ INFO] [1616142201.111114809]: Plugin obstacle_distance loaded
[ INFO] [1616142201.112922023]: Plugin obstacle_distance initialized
[ INFO] [1616142201.113047034]: Plugin odom loaded
[ INFO] [1616142201.116482484]: Plugin odom initialized
[ INFO] [1616142201.116612027]: Plugin onboard_computer_status loaded
[ INFO] [1616142201.118191096]: Plugin onboard_computer_status initialized
[ INFO] [1616142201.118319776]: Plugin param loaded
[ INFO] [1616142201.120770383]: Plugin param initialized
[ INFO] [1616142201.120894989]: Plugin play_tune loaded
[ INFO] [1616142201.124721981]: Plugin play_tune initialized
[ INFO] [1616142201.124860698]: Plugin px4flow loaded
[ INFO] [1616142201.129702305]: Plugin px4flow initialized
[ INFO] [1616142201.129784255]: Plugin rangefinder blacklisted
[ INFO] [1616142201.129881060]: Plugin rc_io loaded
[ INFO] [1616142201.132221241]: Plugin rc_io initialized
[ INFO] [1616142201.132300670]: Plugin safety_area blacklisted
[ INFO] [1616142201.132401780]: Plugin setpoint_accel loaded
[ INFO] [1616142201.134492177]: Plugin setpoint_accel initialized
[ INFO] [1616142201.134641416]: Plugin setpoint_attitude loaded
INFO  [dataman] Unknown restart, data manager file './dataman' size is 11798680 bytes
[ INFO] [1616142201.145566796]: Plugin setpoint_attitude initialized
[ INFO] [1616142201.145739594]: Plugin setpoint_position loaded
INFO  [simulator] Waiting for simulator to accept connection on TCP port 4560
[ INFO] [1616142201.159955620]: Plugin setpoint_position initialized
[ INFO] [1616142201.160130814]: Plugin setpoint_raw loaded
[ INFO] [1616142201.166169709]: Plugin setpoint_raw initialized
[ INFO] [1616142201.166342169]: Plugin setpoint_trajectory loaded
[ INFO] [1616142201.169458669]: Plugin setpoint_trajectory initialized
[ INFO] [1616142201.169620883]: Plugin setpoint_velocity loaded
[ INFO] [1616142201.173810204]: Plugin setpoint_velocity initialized
[ INFO] [1616142201.173990237]: Plugin sys_status loaded
[ INFO] [1616142201.180829857]: Plugin sys_status initialized
[ INFO] [1616142201.181000033]: Plugin sys_time loaded
[ INFO] [1616142201.185481886]: TM: Timesync mode: MAVLINK
[ INFO] [1616142201.186525528]: Plugin sys_time initialized
[ INFO] [1616142201.186684803]: Plugin trajectory loaded
[ INFO] [1616142201.192721783]: Plugin trajectory initialized
[ INFO] [1616142201.192891064]: Plugin vfr_hud loaded
[ INFO] [1616142201.193441225]: Plugin vfr_hud initialized
[ INFO] [1616142201.193525938]: Plugin vibration blacklisted
[ INFO] [1616142201.193628438]: Plugin vision_pose_estimate loaded
[ INFO] [1616142201.198698471]: Plugin vision_pose_estimate initialized
[ INFO] [1616142201.198854561]: Plugin vision_speed_estimate loaded
[ INFO] [1616142201.201214890]: Plugin vision_speed_estimate initialized
[ INFO] [1616142201.201372076]: Plugin waypoint loaded
[ INFO] [1616142201.204727282]: Plugin waypoint initialized
[ INFO] [1616142201.204878804]: Plugin wheel_odometry loaded
[ INFO] [1616142201.213785761]: Plugin wheel_odometry initialized
[ INFO] [1616142201.213947726]: Plugin wind_estimation loaded
[ INFO] [1616142201.215347466]: Plugin wind_estimation initialized
[ INFO] [1616142201.215463819]: Autostarting mavlink via USB on PX4
[ INFO] [1616142201.215614367]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1616142201.215680554]: Built-in MAVLink package version: 2021.2.15
[ INFO] [1616142201.215742083]: Known MAVLink dialects: common ardupilotmega ASLUAV all autoquad icarous matrixpilot paparazzi standard uAvionix ualberta
[ INFO] [1616142201.215801229]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ INFO] [1616142201.245555121]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1616142201.247390758]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1616142201.309816184]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1616142201.311193946]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[INFO] [1616142201.650091, 0.000000]: Loading model XML from file /home/ananthu/Downloads/PX4-Autopilot/Tools/sitl_gazebo/models/quad_f450_camera/quad_f450_camera.sdf
[INFO] [1616142201.658043, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[ INFO] [1616142201.984439037]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1616142202.001958496]: Physics dynamic reconfigure ready.
[INFO] [1616142202.261594, 0.000000]: Calling service /gazebo/spawn_sdf_model

**Comment by MikeS96** [comment]
Hi @jashshah999 

This problem usually happens when the world or model files are not found by the launch file. Please follow the instructions carefully and check if both are properly located in the project's folder.
