### ISSUE TITLE
Building error: States.h file not found

### ISSUE THREAD

**Issue by vishalwins** [MikeS96/autonomous_landing_uav#6]
Hi,

Thanks for sharing the wonderful project. While building the packages using "catkin_make", I am getting the following errors:

[ 61%] Building CXX object CMakeFiles/pid_controller_final.dir/src/pid_controller_final.cpp.o
/home/vishal/catkin_ws/src/drone_controller/src/proportional_traslation.cpp:35:10: fatal error: object_detector/States.h: No such file or directory
 #include "object_detector/States.h" // Custom msgs of type States
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/vishal/catkin_ws/src/drone_controller/src/pid_controller_final.cpp:33:10: fatal error: object_detector/States.h: No such file or directory
 #include "object_detector/States.h" // Custom msgs of type States
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vishal/catkin_ws/src/drone_controller/src/proportional_controller.cpp:33:10: fatal error: object_detector/States.h: No such file or directory
 #include "object_detector/States.h" // Custom msgs of type States
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vishal/catkin_ws/src/drone_controller/src/proportional_rotate.cpp:34:10: fatal error: object_detector/States.h: No such file or directory
 #include "object_detector/States.h" // Custom msgs of type States
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.

The repository doesn't contain this "States.h" file. Request you to please help in resolving this error.

**Comment by MikeS96** [comment]
Hi @vishalwins,

Thank you for the message. The file `States.h` is build with `autonomous_landing_uav/object_detector/msg/States.msg`. Once the project is build, States.h is generated and this file is used by drone_controller's package. 

I advice you to first build the object_detector package and afterwards the drone_controller package. Once you have successfully built object_detector the error should be gone.

**Comment by vishalwins** [comment]
Thank you so much. It worked. :)
