### ISSUE TITLE
rosdep error!

### ISSUE THREAD

**Issue by mohammadrezaaerospace** [MikeS96/autonomous_landing_uav#8]
Hi Mike, I did it all steps in this project but have a problem in final step .
When I run this command for launching:
$roslaunch mavros_off_board mavros_posix_sitl.launch

This error apears:
RLException: [mavros_posix_sitl.launch] is neither a launch file in package [mavros_off_board] nor is [mavros_off_board] a launch file name
The traceback for the exception was written to the log file
what is the problem? Did I missed any steps or is there any fault?
Best Regards

**Comment by MikeS96** [comment]
Hi @mohammadrezaaerospace,

It seems like a "sourcing" issue. The file you are trying to launch is effectively located at `mavros_off_board/launch/mavros_posix_sitl.launch`. Is your catkin workspace named `catkin_ws`? If it has a different name, in the [command](https://github.com/MikeS96/autonomous_landing_uav/blob/master/Usage.md) `source ~/catkin_ws/devel/setup.bash` you will have to change the "catkin_ws" with the name of the folder of your catkin workspace.

**Comment by mohammadrezaaerospace** [comment]
> Hi @mohammadrezaaerospace,
> 
> It seems like a "sourcing" issue. The file you are trying to launch is effectively located at `mavros_off_board/launch/mavros_posix_sitl.launch`. Is your catkin workspace named `catkin_ws`? If it has a different name, in the [command](https://github.com/MikeS96/autonomous_landing_uav/blob/master/Usage.md) `source ~/catkin_ws/devel/setup.bash` you will have to change the "catkin_ws" with the name of the folder of your catkin workspace.

Hi @MikeS96 
The folder name is exactly catkin_ws but I still have this problem!

**Comment by mohammadrezaaerospace** [comment]
@MikeS96 
Also running these commands: 
cd catkin_ws
source devel/setup.bash
gives these error:
ERROR: Rosdep cannot find all required resources to answer your query
Missing resource mavros_off_board
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/mrm/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share
