### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by Mugua12-7** [MikeS96/autonomous_landing_uav#9]
Hi Mike,
I finished all the work carefully according to your instructions, but I still encountered several problems:
Question 1:
When I run successfully
When I run
roslaunch mavros_ off_ board mavros_ posix_ sitl.launch
Grassland cannot be loaded in the environment file of gazebo simulation, as shown in the figure:
![2021-10-21 20-14-32屏幕截图](https://user-images.githubusercontent.com/61924717/138275300-354ea599-8c22-4a03-891a-14761d437809.png)

Question 2:
$ rosrun mavros_ off_ board offb_ node
Tips:
[ WARN] [1634817963.230272247, 3027.021000000]: CMD: Unexpected command 176, result 0
WARN  [mc_pos_control] Offboard activation failed with error: Activation Failed
WARN  [mc_pos_control] Position-Ctrl activation failed with error: Activation Failed
WARN  [mc_pos_control] Altitude-Ctrl activation failed with error: Activation Failed
Question 3:
When I run
$ rosrun mavros_ off_ board teleop_ node_ pos
Tips:
[rosrun] Couldn't find executable named teleop_ node_ pos below /home/yang/catkin_ ws/src/mavros_ off_ board
Question 4:
$ roslaunch object_ detector simu.launch
Tips:
[ERROR] [1634817977.334352109]: No objects loaded from path "/home/sherlock/Documents/Templates/simulation"
Gtk-Message: 20:06:17.423: Failed to load module "canberra-gtk-module"
These questions are bothering me very much. Thank you very much for your help. I wish you a happy life

**Comment by MikeS96** [comment]
Hi @Mugua12-7,

Sorry for the late response. 

Please do not use the beta version, use the stable release of version [v1.11.0](https://github.com/PX4/PX4-Autopilot/releases/tag/v1.11.0). Also, make sure to do all the installation procedures again after checking out v1.11.0 of the Firmware. If the problem persists, please delete [these lines](https://github.com/MikeS96/autonomous_landing_uav/blob/master/mavros_off_board/sdf/quad_f450_camera.sdf#:~:text=%3Cplugin%20name%3D%22GstCameraPlugin,%3C/plugin%3E) in the sdf file and try again.

**Comment by Mugua12-7** [comment]
Hello, I tried to reinstall firmware and check the version. After trying to run, the following errors occurred. I found the answer to the same question in other answers, but it didn't work after trying to solve it. I'm very confused. Thank you.
![Uploading 2021-11-12 16-46-25屏幕截图.png…]()

**Comment by Mugua12-7** [comment]
Hello, I tried to reinstall firmware and check the version. After trying to run, the following errors occurred. I found the answer to the same question in other answers, but it didn't work after trying to solve it. I'm very confused. Thank you.
![2021-11-12 16-46-25屏幕截图](https://user-images.githubusercontent.com/61924717/141438697-63c42741-ebec-4b43-8c09-02f79fafa89e.png)

**Comment by MikeS96** [comment]
Your error is a bit weird. I would suggest deleting the Nuttx Installation and moving your Firmware commit to the specific tag 11.1. Otherwise, I am sure it will not work at all. Sorry for the long delay in the response.

**Comment by Mugua12-7** [comment]
Hello Mike, I saw that the questioner of question [12](https://github.com/MikeS96/autonomous_landing_uav/issues/12) solved [11](https://github.com/MikeS96/autonomous_landing_uav/issues/11) my question and the question he encountered are the same problem, but his method of solving the problem is not the same as the method you gave, I feel Very confused, and his description of the method to solve the problem is not clear, if you can, can I explain my confusion in detail, thank you very much

**Comment by Mugua12-7** [comment]
Hi Mike, I solved all the problems I encountered. Thank you for your help. When I start
 $roslaunch object_ detector simu. 
When launching, the target will not be detected. The following is an error screenshot.
![2021-12-28 20-33-25屏幕截图](https://user-images.githubusercontent.com/61924717/147567166-121ede3a-e1cd-4808-a9bc-e9843e677e6a.png)

Best

**Comment by MikeS96** [comment]
Hi @Mugua12-7,

Glad to hear you solved the issues. I wonder if this is not too much to ask but can you please detail a bit what steps were taken in order to launch the project? 

Regarding your issue, it is because you need to tune a bit the parameters of the object detector. For reference, I used the next ones:

![Screenshot from 2021-12-28 10-38-21](https://user-images.githubusercontent.com/46878806/147582569-51095f3b-7816-4ece-9e06-3ce3fc06ecb7.png)

![Screenshot from 2021-12-28 10-38-51](https://user-images.githubusercontent.com/46878806/147582675-fd31d13e-f4b4-431e-b886-20f541ceb079.png)

![Screenshot from 2021-12-28 10-39-30](https://user-images.githubusercontent.com/46878806/147582677-ac509001-9041-46fa-a287-895b39352614.png)

Hope it helps!

**Comment by Mugua12-7** [comment]
Hi Mike, I'm a beginner. I'll ignore many basic questions. Thank you very much for your help during this time. Because the process is very long, I'll organize it into an email and send it to you.


First execute the following command



&nbsp; &nbsp; cd Firmware&nbsp;&nbsp;
&nbsp; &nbsp; DONT_RUN=1 make px4_sitl_default gazebo&nbsp;&nbsp;
&nbsp; &nbsp; source ~/catkin_ws/devel/setup.bash&nbsp;&nbsp;
&nbsp; &nbsp; source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default&nbsp;&nbsp;
&nbsp; &nbsp; export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)&nbsp;&nbsp;
&nbsp; &nbsp; export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)/Tools/sitl_gazebo
&nbsp; &nbsp; roslaunch mavros_off_board mavros_posix_sitl.launch



give the result as follows




px4 starting.


INFO&nbsp; [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
process[gazebo-3]: started with pid [7026]
INFO&nbsp; [param] selected parameter default file eeprom/parameters_1025
process[gazebo_gui-4]: started with pid [7037]
[param] Loaded: eeprom/parameters_1025
process[vehicle_spawn_yang_Dell_G15_5515_6952_295509135982223110-5]: started with pid [7048]
process[mavros-6]: started with pid [7055]
process[image_view-7]: started with pid [7065]
[ INFO] [1640864981.395371406]: Initializing nodelet with 16 worker threads.
[ INFO] [1640864981.421150287]: FCU URL: ***@***.***:14557
[ INFO] [1640864981.422505185]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1640864981.422629616]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1640864981.422787982]: GCS bridge disabled
[ INFO] [1640864981.429663056]: Plugin 3dr_radio loaded
[ INFO] [1640864981.431783982]: Plugin 3dr_radio initialized
[ INFO] [1640864981.431875149]: Plugin actuator_control loaded
[ INFO] [1640864981.434446574]: Plugin actuator_control initialized
[ INFO] [1640864981.437070008]: Plugin adsb loaded
[ INFO] [1640864981.440643324]: Plugin adsb initialized
[ INFO] [1640864981.440736642]: Plugin altitude loaded
[ INFO] [1640864981.441664329]: Plugin altitude initialized
[ INFO] [1640864981.441766063]: Plugin cam_imu_sync loaded
[ INFO] [1640864981.442101237]: Plugin cam_imu_sync initialized
[ INFO] [1640864981.442474640]: Plugin command loaded
INFO&nbsp; [dataman] Unknown restart, data manager file './dataman' size is 11798680 bytes
[ INFO] [1640864981.449372500]: Plugin command initialized
[ INFO] [1640864981.449481710]: Plugin companion_process_status loaded
INFO&nbsp; [simulator] Waiting for simulator to accept connection on TCP port 4560
[ INFO] [1640864981.451409566]: Plugin companion_process_status initialized
[ INFO] [1640864981.451474183]: Plugin debug_value loaded
[ INFO] [1640864981.454344977]: Plugin debug_value initialized
[ INFO] [1640864981.454375629]: Plugin distance_sensor blacklisted
[ INFO] [1640864981.454448182]: Plugin esc_status loaded
[ INFO] [1640864981.455142228]: Plugin esc_status initialized
[ INFO] [1640864981.455205985]: Plugin esc_telemetry loaded
[ INFO] [1640864981.455558772]: Plugin esc_telemetry initialized
[ INFO] [1640864981.455638550]: Plugin fake_gps loaded
[ INFO] [1640864981.464894461]: Plugin fake_gps initialized
[ INFO] [1640864981.465025927]: Plugin ftp loaded
[ INFO] [1640864981.469023672]: Plugin ftp initialized
[ INFO] [1640864981.469118381]: Plugin geofence loaded
[ INFO] [1640864981.471108433]: Plugin geofence initialized
[ INFO] [1640864981.471206394]: Plugin global_position loaded
[ INFO] [1640864981.482983403]: Using transport "raw"
[ INFO] [1640864981.488479422]: Plugin global_position initialized
[ INFO] [1640864981.488616902]: Plugin gps_input loaded
[ INFO] [1640864981.491777237]: Plugin gps_input initialized
[ INFO] [1640864981.491902798]: Plugin gps_rtk loaded
[ INFO] [1640864981.494053427]: Plugin gps_rtk initialized
[ INFO] [1640864981.494313737]: Plugin gps_status loaded
[ INFO] [1640864981.495935610]: Plugin gps_status initialized
[ INFO] [1640864981.496041557]: Plugin hil loaded
[ INFO] [1640864981.505027050]: Plugin hil initialized
[ INFO] [1640864981.505192451]: Plugin home_position loaded
[ INFO] [1640864981.508605290]: Plugin home_position initialized
[ INFO] [1640864981.508817115]: Plugin imu loaded
[ INFO] [1640864981.513819643]: Plugin imu initialized
[ INFO] [1640864981.513957854]: Plugin landing_target loaded
[ INFO] [1640864981.523614977]: Plugin landing_target initialized
[ INFO] [1640864981.523766898]: Plugin local_position loaded
[ INFO] [1640864981.528703988]: Plugin local_position initialized
[ INFO] [1640864981.528799428]: Plugin log_transfer loaded
[ INFO] [1640864981.530892144]: Plugin log_transfer initialized
[ INFO] [1640864981.530978257]: Plugin mag_calibration_status loaded
[ INFO] [1640864981.531516379]: Plugin mag_calibration_status initialized
[ INFO] [1640864981.531576353]: Plugin manual_control loaded
[ INFO] [1640864981.533001913]: Plugin manual_control initialized
[ INFO] [1640864981.533054451]: Plugin mocap_pose_estimate loaded
[ INFO] [1640864981.535973430]: Plugin mocap_pose_estimate initialized
[ INFO] [1640864981.536061224]: Plugin mount_control loaded
[ INFO] [1640864981.538521128]: Plugin mount_control initialized
[ INFO] [1640864981.538663632]: Plugin nav_controller_output loaded
[ INFO] [1640864981.539285476]: Plugin nav_controller_output initialized
[ INFO] [1640864981.539393965]: Plugin obstacle_distance loaded
[ INFO] [1640864981.541081205]: Plugin obstacle_distance initialized
[ INFO] [1640864981.541181228]: Plugin odom loaded
[ INFO] [1640864981.545128637]: Plugin odom initialized
[ INFO] [1640864981.545222856]: Plugin onboard_computer_status loaded
[ INFO] [1640864981.546566816]: Plugin onboard_computer_status initialized
[ INFO] [1640864981.546688154]: Plugin param loaded
[ INFO] [1640864981.548248462]: Plugin param initialized
[ INFO] [1640864981.548308186]: Plugin play_tune loaded
[ INFO] [1640864981.549390025]: Plugin play_tune initialized
[ INFO] [1640864981.549437570]: Plugin px4flow loaded
[ INFO] [1640864981.553132734]: Plugin px4flow initialized
[ INFO] [1640864981.553226513]: Plugin rallypoint loaded
[ INFO] [1640864981.555134404]: Plugin rallypoint initialized
[ INFO] [1640864981.555171211]: Plugin rangefinder blacklisted
[ INFO] [1640864981.555311423]: Plugin rc_io loaded
[ INFO] [1640864981.557277137]: Plugin rc_io initialized
[ INFO] [1640864981.557305928]: Plugin safety_area blacklisted
[ INFO] [1640864981.557451034]: Plugin setpoint_accel loaded
[ INFO] [1640864981.559337320]: Plugin setpoint_accel initialized
[ INFO] [1640864981.559490231]: Plugin setpoint_attitude loaded
[ INFO] [1640864981.563897766]: Plugin setpoint_attitude initialized
[ INFO] [1640864981.564054820]: Plugin setpoint_position loaded
[ INFO] [1640864981.572241341]: Plugin setpoint_position initialized
[ INFO] [1640864981.572447552]: Plugin setpoint_raw loaded
[ INFO] [1640864981.576687004]: Plugin setpoint_raw initialized
[ INFO] [1640864981.576911347]: Plugin setpoint_trajectory loaded
[ INFO] [1640864981.579531508]: Plugin setpoint_trajectory initialized
[ INFO] [1640864981.579760335]: Plugin setpoint_velocity loaded
[ INFO] [1640864981.582720364]: Plugin setpoint_velocity initialized
[ INFO] [1640864981.582888186]: Plugin sys_status loaded
[ INFO] [1640864981.589881426]: Plugin sys_status initialized
[ INFO] [1640864981.590143477]: Plugin sys_time loaded
[ INFO] [1640864981.593432246]: TM: Timesync mode: MAVLINK
[ INFO] [1640864981.594688032]: Plugin sys_time initialized
[ INFO] [1640864981.594899126]: Plugin trajectory loaded
[ INFO] [1640864981.600617196]: Plugin trajectory initialized
[ INFO] [1640864981.600817412]: Plugin vfr_hud loaded
[ INFO] [1640864981.601417880]: Plugin vfr_hud initialized
[ INFO] [1640864981.601453636]: Plugin vibration blacklisted
[ INFO] [1640864981.601515922]: Plugin vision_pose_estimate loaded
[ INFO] [1640864981.605720278]: Plugin vision_pose_estimate initialized
[ INFO] [1640864981.605989724]: Plugin vision_speed_estimate loaded
[ INFO] [1640864981.607864522]: Plugin vision_speed_estimate initialized
[ INFO] [1640864981.608046234]: Plugin waypoint loaded
[ INFO] [1640864981.610961751]: Plugin waypoint initialized
[ INFO] [1640864981.611195661]: Plugin wheel_odometry loaded
[ INFO] [1640864981.621568466]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1640864981.622546489]: Plugin wheel_odometry initialized
[ INFO] [1640864981.622661633]: Plugin wind_estimation loaded
[ INFO] [1640864981.623246230]: Plugin wind_estimation initialized
[ INFO] [1640864981.623326919]: Autostarting mavlink via USB on PX4
[ INFO] [1640864981.623361594]: Built-in SIMD instructions: SSE, SSE2
[ INFO] [1640864981.623373783]: Built-in MAVLink package version: 2021.10.10
[ INFO] [1640864981.623394878]: Known MAVLink dialects: common ardupilotmega ASLUAV all development icarous matrixpilot paparazzi standard uAvionix ualberta
[ INFO] [1640864981.623409099]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ INFO] [1640864981.623797132]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1640864981.657050224]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1640864981.658397196]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1640864981.870761998]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1640864981.887477919, 2755.377000000]: Physics dynamic reconfigure ready.
[INFO] [1640864982.043276, 0.000000]: Loading model XML from file /home/yang/Firmware/Tools/sitl_gazebo/models/quad_f450_camera/quad_f450_camera.sdf
[INFO] [1640864982.055648, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[INFO] [1640864982.063042, 2755.545000]: Calling service /gazebo/spawn_sdf_model
[ INFO] [1640864982.644261908, 2755.721000000]: Camera Plugin: Using the 'robotNamespace' param: 'quad_f450_camera'
[ INFO] [1640864982.647891038, 2755.721000000]: Camera Plugin (ns = quad_f450_camera)&nbsp; <tf_prefix_&gt;, set to "quad_f450_camera"
[INFO] [1640864982.681004, 2755.721000]: Spawn status: SpawnModel: Successfully spawned entity
10.80
INFO&nbsp; [simulator] Simulator connected on TCP port 4560.
INFO&nbsp; [commander] LED: open /dev/led0 failed (22)
INFO&nbsp; [init] Mixer: etc/mixers/quad_w.main.mix on /dev/pwm_output0
INFO&nbsp; [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 18570 remote port 14550
[vehicle_spawn_yang_Dell_G15_5515_6952_295509135982223110-5] process has finished cleanly
log file: /home/yang/.ros/log/926c2ac8-6966-11ec-a1e6-f85ea04a48c2/vehicle_spawn_yang_Dell_G15_5515_6952_295509135982223110-5*.log
INFO&nbsp; [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14580 remote port 14540
INFO&nbsp; [mavlink] mode: Onboard, data rate: 4000 B/s on udp port 14280 remote port 14030
INFO&nbsp; [logger] logger started (mode=all)
INFO&nbsp; [logger] removing log directory ./log/2021-12-17 to get more space (left=18219 MiB)
INFO&nbsp; [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
INFO&nbsp; [logger] Start file log (type: full)
INFO&nbsp; [logger] [logger] ./log/2021-12-30/11_49_43.ulg
INFO&nbsp; [logger] Opened full log file: ./log/2021-12-30/11_49_43.ulg
INFO&nbsp; [px4] Startup script returned successfully
pxh&gt; [ INFO] [1640864983.023610328, 2755.925000000]: udp0: Remote address: 127.0.0.1:14580
[ INFO] [1640864983.023719657, 2755.925000000]: IMU: High resolution IMU detected!
INFO&nbsp; [mavlink] partner IP: 127.0.0.1
[ INFO] [1640864984.012868162, 2756.893000000]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ INFO] [1640864984.025366340, 2756.901000000]: IMU: High resolution IMU detected!
INFO&nbsp; [ecl/EKF] 996000: GPS checks passed
[ INFO] [1640864985.058391275, 2757.901000000]: GF: Using MISSION_ITEM_INT
[ INFO] [1640864985.058852719, 2757.901000000]: RP: Using MISSION_ITEM_INT
[ INFO] [1640864985.058954242, 2757.901000000]: WP: Using MISSION_ITEM_INT
[ INFO] [1640864985.059029036, 2757.901000000]: VER: 1.1: Capabilities&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0x000000000000e4ef
[ INFO] [1640864985.059056186, 2757.901000000]: VER: 1.1: Flight software:&nbsp; &nbsp; &nbsp;010b0000 (71db0903a9000000)
[ INFO] [1640864985.059073448, 2757.901000000]: VER: 1.1: Middleware software: 010b0000 (71db0903a9000000)
[ INFO] [1640864985.059100638, 2757.901000000]: VER: 1.1: OS software:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;050400ff (ec20f2e6c5cc35b2)
[ INFO] [1640864985.059115769, 2757.901000000]: VER: 1.1: Board hardware:&nbsp; &nbsp; &nbsp; 00000001
[ INFO] [1640864985.059129208, 2757.901000000]: VER: 1.1: VID/PID:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0000:0000
[ INFO] [1640864985.059139226, 2757.901000000]: VER: 1.1: UID:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;4954414c44494e4f
[ WARN] [1640864985.061856809, 2757.901000000]: CMD: Unexpected command 520, result 0
INFO&nbsp; [ecl/EKF] 3080000: EKF aligned, (baro hgt, IMU buf: 18, OBS buf: 14)
INFO&nbsp; [ecl/EKF] 3080000: reset position to last known position
INFO&nbsp; [ecl/EKF] 3080000: reset velocity to zero
[ INFO] [1640864986.153897695, 2758.977000000]: IMU: Attitude quaternion IMU detected!
INFO&nbsp; [ecl/EKF] 5288000: reset position to GPS
INFO&nbsp; [ecl/EKF] 5288000: reset velocity to GPS
INFO&nbsp; [ecl/EKF] 5288000: starting GPS fusion
[ INFO] [1640864999.219403183, 2771.893000000]: GF: mission received
[ INFO] [1640864999.219529012, 2771.893000000]: RP: mission received
[ INFO] [1640864999.219575135, 2771.893000000]: WP: mission received







Then create two new terminals and execute the following commands respectively


rosrun mavros_ off_ board offb_ node


rosrun mavros_ off_ board teleop_ node_ pos



give the result as follows



and

When I want to press WSAD and IJKL to control his movement or U / m to control the altitude, the UAV will not move, and the following prompt appears:

When I use the takeoff / landing command, he will land / take off, return to the origin and hover




Px4 display:

When I start a new terminal and start


roslaunch object_ detector simu. launch


When deploying according to your parameters, I found that I could not select the "surf" of the descriptor and could not detect the target, as shown in the figure










My questions are as follows:


1： How can I correctly recognize the apriltag icon


2： How can I control UAV flight and automatic identification landing






Thank you very much for your patience in reading all the above contents, and thank you very much for your help. I wish you success in your work

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MikeS96/autonomous_landing_uav"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月28日(星期二) 晚上11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MikeS96/autonomous_landing_uav] Several questions (Issue #9)





 
Hi @Mugua12-7,
 
Glad to hear you solved the issues. I wonder if this is not too much to ask but can you please detail a bit what steps were taken in order to launch the project?
 
Regarding your issue, it is because you need to tune a bit the parameters of the object detector. For reference, I used the next ones:
 

 

 

 
Hope it helps!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MikeS96** [comment]
Hi @Mugua12-7,

1. To recognize the April tag there is some tune needed in the object detection GUI. The images are a base but you can use whichever detector/descriptor you prefer. I would say that the most important parameters are the ones in Homography and Nearest Neighbors, however, you can find different configurations and make it work. To use SURF you will have to install opencv from source.

2. Control the UAV is not that easy as the scripts are not so well developed and were more for testing purposes, however, you should be able to control it by launching `offb_ node` and then `teleop_ node_ pos`. Note that it is super important to shut down the terminal with `offb_ node`, otherwise, you will not be able to teleoperate it. 

Best.

**Comment by Mugua12-7** [comment]
Hi Mike.
I'm sorry to reply to your email so late. Thank you very much for your help and reply. These suggestions are very effective, but I still can't solve the problem of object detection. I have reinstalled OpenCV 3.4.16 and adjusted the parameters. I still can't use descriptors such as SURF. I've attached my parameters and results below, and I hope to get your help.&nbsp;








Best.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MikeS96/autonomous_landing_uav"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月31日(星期五) 凌晨1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MikeS96/autonomous_landing_uav] Several questions (Issue #9)





 
Hi @Mugua12-7,
  
 
To recognize the April tag there is some tune needed in the object detection GUI. The images are a base but you can use whichever detector/descriptor you prefer. I would say that the most important parameters are the ones in Homography and Nearest Neighbors, however, you can find different configurations and make it work. To use SURF you will have to install opencv from source.
 
 
 
Control the UAV is not that easy as the scripts are not so well developed and were more for testing purposes, however, you should be able to control it by launching offb_ node and then teleop_ node_ pos. Note that it is super important to shut down the terminal with offb_ node, otherwise, you will not be able to teleoperate it.
 
  
Best.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mugua12-7** [comment]
Hi Mike.
I'm sorry to reply to your so late. Thank you very much for your help and reply. These suggestions are very effective, but I still can't solve the problem of object detection. I have reinstalled OpenCV 3.4.16 and adjusted the parameters. I still can't use descriptors such as SURF. I've attached my parameters and results below, and I hope to get your help.

![image](https://user-images.githubusercontent.com/61924717/149766307-1b9a64c5-9aaa-4580-aeac-fdacf9e6bc85.png)
![image](https://user-images.githubusercontent.com/61924717/149766322-d4976c76-05f8-4b30-b884-b6fd96f86a86.png)
![image](https://user-images.githubusercontent.com/61924717/149766338-d4d05c10-3b4d-45bc-bddc-582083ad82ec.png)
![image](https://user-images.githubusercontent.com/61924717/149766363-ec265273-dde5-4ebf-bedc-8795c1ebdd30.png)
![image](https://user-images.githubusercontent.com/61924717/149766380-ddb02452-f189-4920-91dd-3d481b060c22.png)
![image](https://user-images.githubusercontent.com/61924717/149766392-16a6c295-bccf-4c79-8f80-c47711d87b37.png)


Best.

**Comment by MikeS96** [comment]
Hi @Mugua12-7,

Try installing it from source [here](https://www.pyimagesearch.com/2018/05/28/ubuntu-18-04-how-to-install-opencv/) is a great guide.

**Comment by Mugua12-7** [comment]
Hi Mike
Thank you for your help. I reinstalled opencv according to your method, but when I simulated, I couldn't call the camera, and the program didn't report specific error information. I'm very confused and hope to get your help. Thank you very much


![2022-01-24 14-03-13屏幕截图](https://user-images.githubusercontent.com/61924717/150730452-f554c0bd-00c5-46c9-a365-e88d738b0da1.png)
When I run roslaunch object_ detector simu. When launching, it will always pause in this part.

 When I open find object 2D, it will display
![2022-01-24 14-08-03屏幕截图](https://user-images.githubusercontent.com/61924717/150730679-8d39f8cd-953a-49db-874c-a66bc8e69723.png)

This is what gazebo shows

![2022-01-24 14-06-00屏幕截图](https://user-images.githubusercontent.com/61924717/150730528-8719adbc-95db-484e-8b23-851520540539.png)

**Comment by MikeS96** [comment]
Hey @Mugua12-7 

In case you are interested, I updated the project to Ubuntu 20 and ROS Noetic on its latest commit 3e36151. Fixed most of the issues discussed lately and manage to make the vehicle fly. Please consider installing OpenCV from source to enable SURF and SIFT descriptors as these provide better detections for the pad.

**Comment by Norton-z** [comment]
> 
Hi @MikeS96 

I also can't use descriptors such as SURF and SIFT in find_object_2d. I have installed OpenCV 3.4.0 from source and install find_object_2d form source in  Ubuntu20 and ROS Noetic. How can I  use descriptors such as SURF and SIFT in find_object_2d to detect the template?
